import type { Metadata } from "next";
import Header from "./components/Header/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "JobHuntly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className="w-full min-h-full"
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
